fix: update command string
Old command cause error on Window:
Error: Command failed: git log -1 --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%ad'
fatal: invalid object name '%H'.

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)